apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: json-parser-stdout-pipeline
spec:
  parsers:
    - content: |
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S %z
  output:
    custom: |
      Name               stdout
  filters:
    - custom: |
        Name    grep
        Regex $kubernetes['namespace_name'] default