apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: tracepipelines.telemetry.kyma-project.io
    busola.io/extension: resource
    busola.io/extension-version: "0.5"
  name: tracepipelines.telemetry.kyma-project.io
  namespace: kube-public
data:
  details: |-
    {
      "header": [
         {
          "source": "$each(spec.output, function($v, $k) {$v.url.value or $v.url.valueFrom.secretKeyRef.name or $v.host.value or $v.host.valueFrom.secretKeyRef.name ? $k})",
          "placeholder": "custom",
          "type": "string",
          "name": "Type",
          "isSelected": true,
          "widget": "Text"
        },
        {
          "name": "Unsupported-Mode",
          "source": "status.unsupportedMode",
          "widget": "Badge",
          "highlights": {
            "positive": ["false"],
            "negative": ["true"]
          }
        },
        {
          "source": "status.conditions[-1].type",
          "name": "Status",
          "widget": "Badge"
        }
      ],
      "body":
        [
          {
            "widget": "Panel",
            "name": "Output",
            "children":
              [
                {
                  "name": "OTLP",
                  "widget": "Panel",
                  "visibility": "$exists(spec.output.otlp)",
                  "children": [
                    {
                      "name": "Value",
                      "source": "spec.output.otlp.endpoint.value",
                      "visibility": "$exists(spec.output.otlp.endpoint.value)",
                    },
                    {
                      "name": "Protocol",
                      "source": "spec.output.otlp.protocol",
                      "visibility": "$exists(spec.output.otlp.protocol)",
                    },
                    {
                      "name": "User",
                      "widget": "Panel",
                      "visibility": "$exists(spec.output.otlp.authentication.basic.user)",
                      "children": [
                        {
                          "name": "Value",
                          "source": "spec.output.otlp.authentication.basic.user.value",
                          "visibility": "$exists(spec.output.otlp.authentication.basic.user.value)"
                        },
                        {
                          "name": "Value From Secret",
                          "widget": "ResourceRefs",
                          "source": "spec.output.otlp.authentication.basic.user.valueFrom.secretKeyRef",
                          "kind": "Secret",
                          "visibility": "$exists(spec.output.otlp.authentication.basic.user.valueFrom.secretKeyRef.name)"
                        }
                      ]
                    },
                    {
                      "name": "Password",
                      "widget": "Panel",
                      "visibility": "$exists(spec.output.otlp.authentication.basic.password)",
                      "children": [
                        {
                          "name": "Value",
                          "source": "spec.output.otlp.authentication.basic.password.value",
                          "visibility": "$exists(spec.output.otlp.authentication.basic.password.value)"
                        },
                        {
                          "name": "Value From Secret",
                          "widget": "ResourceRefs",
                          "source": "spec.output.otlp.authentication.basic.password.valueFrom.secretKeyRef",
                          "kind": "Secret",
                          "visibility": "$exists(spec.output.otlp.authentication.basic.password.valueFrom.secretKeyRef.name)"
                        }
                      ]
                    }
                  ]
                },
              ]
          }
        ]
    }
  form: |
    [
      {
        "path": "spec.output",
        "widget": "FormGroup",
        "path": "spec.output",
        "defaultExpanded": true,
        "simple": true,
        "children":
          [
            {
              "name": "OTLP",
              "path": "otlp",
              "widget": "FormGroup",
              "defaultExpanded": true,
              "simple": true,
              "children":
                [
                  {
                    "name": "Endpoint",
                    "path": "endpoint",
                    "widget": "FormGroup",
                    "children":
                      [
                        {
                          "name": "Value",
                          "path": "value",
                          "widget": "Text"
                        },
                        {
                          "name": "Secret Reference",
                          "path": "valueFrom.secretKeyRef",
                          "widget": "ResourceRef",
                          "resource": {
                             "kind": "secret",
                             "version": "v1",
                          },
                          "children": [{
                              "path": "key",
                              "enum": "$keys($secret.data)",
                          },
                          ],
                        }
                      ]
                  },
                  {
                    "name": "Protocol",
                    "path": "protocol",
                    "widget": "FormGroup",
                    "children": 
                      [
                        {
                          "name": "Value",
                          "widget": "Text"
                        }
                      ]
                  },
                  {
                    "name": "User",
                    "path": "authentication.basic.user",
                    "widget": "FormGroup",
                    "children":
                      [
                        {
                          "name": "Value",
                          "path": "value",
                          "widget": "Text"
                        },
                        {
                          "name": "Secret Reference",
                          "path": "valueFrom.secretKeyRef",
                          "widget": "ResourceRef",
                          "resource": {
                             "kind": "secret",
                             "version": "v1",
                          },
                          "children": [{
                              "path": "key",
                              "enum": "$keys($secret.data)",
                          },
                          ],
                        }
                      ]
                  },
                  {
                    "name": "Password",
                    "path": "authentication.basic.password",
                    "widget": "FormGroup",
                    "children":
                      [
                        {
                          "name": "Value",
                          "path": "value",
                          "widget": "Text"
                        },
                        {
                          "name": "Secret Reference",
                          "path": "valueFrom.secretKeyRef",
                          "widget": "ResourceRef",
                          "resource": {
                             "kind": "secret",
                             "version": "v1",
                          },
                          "children": [{
                              "path": "key",
                              "enum": "$keys($secret.data)",
                          },
                          ],
                        }
                      ]
                  },
                  {
                    "name": "TLS",
                    "widget": "FormGroup",
                    "path": "tls",
                    "children":
                      [
                        {
                          "name": "Disabled",
                          "path": "disabled"
                        },
                        {
                          "name": "Skip Certificate Validation",
                          "path": "skipCertificateValidation"
                        }
                      ]
                  },
                  {
                    "name": "URI",
                    "path": "uri",
                    "widget": "Text"
                  },
                  {
                    "name": "Port",
                    "path": "port",
                    "widget": "Text"
                  },
                  {
                    "name": "Compress",
                    "path": "compress",
                    "widget": "Text"
                  },
                  {
                    "name": "Format",
                    "path": "format",
                    "widget": "Text"
                  },
                  {
                    "name": "Dedot",
                    "path": "dedot"
                  },
                ]
            },
          ]
      }
    ]
  general: |-
    {
      "resource": {
        "kind": "TracePipeline",
        "group": "telemetry.kyma-project.io",
        "version": "v1alpha1"
      },
      "name": "Trace Pipelines",
      "category": "Observability",
      "urlPath": "tracepipelines",
      "scope": "cluster",
      "description": "Configure custom Trace Pipeline",
    }
  list: |-
    [
      {
        "source": "status.conditions[-1].type",
        "name": "Status",
        "widget": "Badge"
      }
    ]
  translations: |-
    {
      "en": {
        "metadata.annotations": "Annotations",
        "metadata.labels": "Labels",
        "metadata.creationTimestamp": "Created at"
      }
    }
